### ISSUE TITLE
Leakage

### ISSUE THREAD

**Issue by barneydobson** [barneydobson/wsi#18]
- [x] Does it mainly go to Groundwater, Soil Tank, or both?
- [x] Should it be on a % basis or something more complicated
- [x] Does this just go into the core Distribution class, or new subclass, or decorator?
- [x] Sewers or distribution only? (for now we will ignore sewers under presumption this exfiltration flow is minimal)

If you have any insight to add or other suggestions, please discuss under this issue

**Comment by zzzzy9** [comment]
- The general assumption is that this is only from mains supply in HERT (leakage from sewage pipes or other forms of drainage (like SUDS) as the contribution tends to be small)

- the total difference in the Upper Lee catchment (upstream of the gauging station at Howe Green, Water Hall) between the naturalised model recharge and the historical model recharge is 8.2Ml/d.  This could be almost entirely attributed to the mains leakage component for the catchment but may include some recharge due to STW discharges to ground as well.

- information from https://www.discoverwater.co.uk/leaking-pipes which gives estimates of leakage per property and per km of main for each water company.

**Comment by barneydobson** [comment]
OK thanks @zzzzy9 - I think for now we'll ignore Sewers then (I suppose in the long run the sewer leakage could still be a pollution source if not a significant flow source - but we can shelf that). 

Thanks for the numbers source, I think an even finer resolution leakage dataset could be available in the WRMP planning tables on request from EA, but it's good that this source is open. I won't try and do any preprocessing at this stage - but instead suggest that people use that data to get an idea of what it might be locally. Though for anyone outside UK who needs a rough idea the range across water resource zones in the UK varies from about 40litres/property/day up to about 200 litres/property/day. 

I'm not super clear on whether these numbers are referring to on-property leakage, distribution network only leakage, or both. I think we will have to assume that these numbers account for both, and we will make all of the leakage come out of the distribution node. (We will note this in any changes made to the node).

It sounds like, at least in the HERT model, they are assuming all of the leakage is going into the groundwater and not into the soil tank - is that right?

Also - don't suppose you have any views on the second task above? i.e., fixed amount? proportional amount? something else? My instinct would be to go with a proportional amount - i.e., leakage is proportional to flow, but then this will mean the leakage is varying due to increased water demand over summer due to garden irrigation.
